---

version: 2

updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "jkatzwinkel"
    open-pull-requests-limit: 10
    groups:
      junit:
        patterns:
          - "org.junit.jupiter:junit-jupiter-*"
      spring-boot:
        patterns:
          - "org.springframework.boot*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jkatzwinkel"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jkatzwinkel"

...
