---

version: 2

updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "spring-boot-autoconfigure"
        versions:
          - "3.0.0-M4"
      - dependency-name: "spring-boot-starter-test"
        versions:
          - "3.0.0-M4"
    reviewers:
      - "jkatzwinkel"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "jkatzwinkel"

...
