---

version: 2

updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "jkatzwinkel"
    open-pull-requests-limit: 10
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:spring-boot-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jkatzwinkel"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jkatzwinkel"
    ignore:
      # this only applies until gradle 8.5 or whichever gradle release
      # introducing java 22 support
      - dependency-name: openjdk
        versions:
          - 22-jdk-slim-bullseye

...
