---
version: '3.7'

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            discovery.type: single-node
        ports:
            - ${ES_PORT}:9200
        stdin_open: true
        tty: true

    app:
        depends_on:
            - elasticsearch
        build:
            context: .
            args:
                - es_port=${ES_PORT}
        ports:
            - 8090:8090
        tty: true
        network_mode: host

