---
version: '3.7'

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            discovery.type: single-node
        ports:
            - ${ES_PORT}:9200
        stdin_open: true
        tty: true

    backend:
        build:
            context: .
            args:
                - es_port=${ES_PORT}
                - es_host=127.0.0.1
                - sample_url=${SAMPLE_URL}
        ports:
            - 8090:8090
        tty: true
        network_mode: host

...
