---
version: '3.7'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            discovery.type: single-node
        ports:
            - 9201:9200
        stdin_open: true
        tty: true


