---

version: '3.7'

services:

  es:
    container_name: tla-es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
      discovery.type: single-node
      xpack.security.enabled: "false"
      ingest.geoip.downloader.enabled: "false"
    ports:
      - ${ES_PORT:-9200}:9200
    restart: unless-stopped

  populate:
    container_name: tla-ingest
    depends_on:
      - es
    build:
      context: .
    environment:
      - ES_HOST=es
      - ES_PORT=9200
      - SAMPLE_URL
    command: "ingest"

  backend:
    container_name: tla-backend
    depends_on:
      - es
    build:
      context: .
    environment:
      - ES_HOST=es
      - ES_PORT=9200
    ports:
      - 8090:8090
    restart: unless-stopped

...
