---

logging:
    file:
        name: app.log

server:
    error:
        whitelabel:
            enabled: false

springdoc:
    swagger-ui:
        path: "/swagger.html"

tla:
    es:
        port: ${ES_PORT:9200}
        host: ${ES_HOST:localhost}

...
