---

name: dependencies

on:  # yamllint disable-line
  push:
    branches:
      - main

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 21

      - name: Submit dependencies
        uses: mikepenz/gradle-dependency-submission@v0.9.1

...
