---

name: searchtest

'on':
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/test/resources/search/**/*.json'
      - 'docker-compose.yml'
      - '.github/workflows/search.yml'
  workflow_dispatch:

env:
  ES_PORT: 9201
  SAMPLE_URL: ${{ vars.DATA_URL }}

jobs:
  search:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Java 21
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Elasticsearch container at port ${{ env.ES_PORT }}
        run: docker compose up -d es

      - name: Install project dependencies
        run: ./gradlew testclasses

      - name: Wait for ES to respond
        run: >
          bash .github/scripts/wait_for_response.sh
          http://localhost:${ES_PORT} 30

      - name: Cache sample corpus data
        uses: actions/cache@v4.0.0
        with:
          path: sample.tar.gz
          key: ${{ env.SAMPLE_URL }}

      - name: Ingest corpus data
        run: ./gradlew populate

      - name: Run search tests
        run: ./gradlew testSearch

...
