---

name: searchtest

on:
  push:
    branches:
      - 'qa'
  # pull_request: {}

jobs:
  search:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Set up JDK 17
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Elasticsearch container
      run: docker-compose up -d es
      env:
        ES_PORT: 9200

    - name: Wait for ES to respond
      run: >
        bash .github/scripts/wait_for_response.sh
        http://localhost:9200 30

    - name: Cache sample corpus data
      uses: actions/cache@v3.2.4
      env:
        cache-name: cache-corpus-data
      with:
        path: sample.tar.gz
        key: ${{ runner.os }}-searchtest-${{ env.cache-name }}-${{ hashFiles('sample.tar.gz') }}
        restore-keys: |
          ${{ runner.os }}-searchtest-${{ env.cache-name }}-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Ingest corpus data
      run: ./gradlew populate
      env:
        ES_PORT: 9200
        SAMPLE_URL: http://aaew64.bbaw.de/resources/tla-data/tla-data-20210115.tar.gz

    - name: Run search tests
      run: ./gradlew testSearch
      env:
        ES_PORT: 9200

...
