---

name: searchtest

'on':
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/test/resources/search/**/*.json'
      - 'docker-compose.yml'
      - '.github/workflows/search.yml'
  workflow_dispatch:

env:
  ES_PORT: 9201
  SAMPLE_URL: ${{ vars.DATA_URL }}

jobs:

  check_url:
    runs-on: ubuntu-latest
    outputs:
      url_response: ${{ steps.check.outputs.response_code }}

    steps:
      - id: check
        run: |
          rc=$(curl -sIo /dev/null "${{ vars.SAMPLE_URL }}" \
          -w "%{http_code}" || true)
          echo "response_code=${rc}" >> "${GITHUB_OUTPUT}"


  search:
    runs-on: ubuntu-latest
    needs: check_url
    if: needs.check_url.outputs.url_response != '404'

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Java 21
        uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Elasticsearch container at port ${{ env.ES_PORT }}
        run: docker compose up -d es

      - name: Install project dependencies
        run: ./gradlew testclasses

      - name: Wait for ES to respond
        run: >
          bash .github/scripts/wait_for_response.sh
          http://localhost:${ES_PORT} 30

      - name: Cache sample corpus data
        uses: actions/cache@v4.2.3
        with:
          path: sample.tar.gz
          key: ${{ env.SAMPLE_URL }}

      - name: Ingest corpus data
        run: ./gradlew populate

      - name: Run search tests
        run: ./gradlew testSearch

      - uses: mikepenz/action-junit-report@v5.6.2
        if: always()
        with:
          report_paths: 'build/test-results/testSearch/TEST-*.xml'

...
