---

name: update elasticsearch service

'on':
  pull_request:
    branches:
      - 'dependabot/**elasticsearch*'
  push:
    branches:
      - 'dependabot/**elasticsearch*'
    paths-ignore:
      - docker-compose.yml
  workflow_call:

jobs:
  update-elasticsearch-service:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed.outputs.changed }}
      ref: ${{ steps.ref.outputs.ref }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2

      - name: install jq/yq
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends jq yq

      - name: get latest elasticsearch version from github
        id: latest
        run: >-
          latest=$(
            curl -s "${GH_RELEASES_PAGE}" |
            jq -r '[.[] | select(.prerelease==false) | .tag_name] | max'
          ); echo "latest=${latest#v}" >> "${GITHUB_OUTPUT}"
        env:
          GH_RELEASES_PAGE: >-
            https://api.github.com/repos/elastic/elasticsearch/releases

      - name: get current version of elasticsearch service
        id: current
        run: |
          cur=$(yq -r .services.es.image docker-compose.yml)
          echo "current=${cur#*:}" >> "${GITHUB_OUTPUT}"

      - name: bump docker compose elasticsearch version
        run: >-
          sed -i 's/\(elasticsearch:\)'${OLD}'/\1'${NEW}'/'
          docker-compose.yml
        env:
          OLD: ${{ steps.current.outputs.current }}
          NEW: ${{ steps.latest.outputs.latest }}

      - name: count changed files
        id: changed
        run: |
          chg=$(git diff --shortstat | wc -l)
          echo "changed=${chg}" >> ${GITHUB_OUTPUT}

      - name: push change
        run: |
          git config user.email "${GIT_MAIL}"
          git config user.name "github-actions[bot]"
          git add docker-compose.yml
          git commit -m "bump elasticsearch from ${OLD} to ${NEW}"
          git push
        env:
          OLD: ${{ steps.current.outputs.current }}
          NEW: ${{ steps.latest.outputs.latest }}
          GIT_MAIL: >-
            41898282+github-actions[bot]@users.noreply.github.com
        if: steps.changed.outputs.changed != '0'

      - name: get branch name && save ref
        id: ref
        run: |
          branch=$(git branch --show-current)
          echo "ref=refs/heads/${branch}" >> ${GITHUB_OUTPUT}


  test:
    needs: [update-elasticsearch-service]
    uses: ./.github/workflows/gradle.yml
    if: needs.update-elasticsearch-service.outputs.changed != '0'
    with:
      ref: ${{ needs.update-elasticsearch-service.outputs.ref }}

...
