---

name: update gradle wrapper

on:
  schedule:
    - cron: "0 0 * * *"

jobs:

  update-gradle-wrapper:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed.outputs.changed }}

    steps:
      - uses: actions/checkout@v4.2.2

      - name: update gradle wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2.1.0
        with:
          pr-title-template: >-
            build(deps): update gradle wrapper from %sourceVersion%
            to %targetVersion%
          commit-message-template: >-
            build(deps): update gradle wrapper from %sourceVersion%
            to %targetVersion%
          labels: dependencies, gradle
          reviewers: jkatzwinkel

      - name: determine change status
        id: changed
        run: |
          chg=$(git diff --shortstat HEAD..main | wc -l)
          echo "changed=${chg}" >> ${GITHUB_OUTPUT}

  post-update-tests:
    runs-on: ubuntu-latest
    needs: [update-gradle-wrapper]
    uses: ./.github/workflows/gradle.yml
    if: needs.update-gradle-wrapper.outputs.changed != '0'

...
